tags:
- name: users
  description: users API

paths:
  /games:
    post:
      summary: Create game
      parameters:
      - name: body
        in: body
        description: game data
        required: true
        schema:
          $ref: '#/definitions/game'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

  /games/{game_id}:
    get:
      summary: Get a game
      parameters:
      - name: game_id
        in: path
        description: Game Id
        required: true
        type: string
      responses:
        200:
          description: game
          content:
            application/json:
              schema:
                $ref: '#/definitions/game'
        500:
          description: 'Server Error'

  /games/{game_id}/answers:
    post:
      summary: Post an answer
      parameters:
      - name: game_id
        in: path
        description: Game Id
        required: true
        type: string
      - name: question_id
        in: query
        description: Question Id
        required: true
        type: string
      - name: answer_id
        in: query
        description: Answer Id
        required: true
        type: string
      - name: participant
        in: query
        description: Participant who answered
        required: true
        type: string
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

definitions:
  game:
    type: object
    required:
        - name
        - access_token
        - channel_id
        - questions
    properties:
      name:
        type: string
        description: game name
      access_token:
        type: string
        description: access token to be used for messaging
      channel_id:
        type: string
        description: channel id to be used for messaging
      questions:
        type: array
        description: questions for the game
        items:
          type: object
          $ref: '#/definitions/question'
  question:
    type: object
    required:
        - question
        - answers
    properties:
      question:
        type: string
        description: question text
      answers:
        type: array
        description: answers for the question
        items:
          type: object
          $ref: '#/definitions/answer'
  answer:
    type: object
    required:
        - answer
    properties:
      answer:
        type: string
        description: answer text
      is_correct:
        type: boolean
        description: is this the correct answer
schemes:
 - https
 - http
